manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: urob
      url-base: https://github.com/urob
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: lazy-dinosaur
      url-base: https://github.com/lazy-dinosaur
  projects:
    - name: zmk
      remote: urob
      revision: main
      import: app/west.yml
    - name: cirque-input-module
      remote: petejohanson
      revision: main
    - name: zmk-helpers
      remote: urob
      revision: v2 # t
    - name: zmk-input-behavior-listener
      remote: badjeff
      revision: main
    - name: zmk-split-peripheral-input-relay
      remote: badjeff
      revision: main
    - name: zmk-config-LazyDino
      remote: lazy-dinosaur
      revision: master
  self:
    path: config
